def error(update, context):
  print(f'Update:{update} caused error:{context.error}')